import Head from 'next/head'
import dynamic from 'next/dynamic'

const World = dynamic(() => import("@/components/world"), { ssr: false })

export default function Library() {
    return (
        <>
            <Head>
                <title>Cybersyn Library</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <World>
                <mesh visible userData={{ hello: 'world' }} position={[1, 2, 3]} rotation={[Math.PI / 2, 0, 0]}>
                    <sphereGeometry args={[1, 16, 16]} />
                    <meshStandardMaterial color="hotpink" transparent />
                </mesh>
                <ambientLight intensity={10} />
                <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
                <pointLight position={[-10, -10, -10]} />
                <spotLight position={[10, 10, 10]} angle={15} penumbra={1} />
            </World>
        </>
    )
}